# -*- coding: utf-8 -*-
"""Copy of fileRead.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iZCySgpjQudqNGUW_bLiep8o5py4pZe2
"""

import pandas as pd
from openpyxl.workbook import Workbook

df_excel = pd.read_excel('regions.xlsx')